### ISSUE TITLE
way off topic but cannot find contact info for you anywhere

### ISSUE THREAD

**Issue by ghost** [MyXoToD/PHP-Database-Class#3]
Sorry to create an issue on this project but I can't find a way to contact you.  I would like the ajax from your codepen chat project.

thank you

**Comment by MyXoToD** [comment]
No need to contact me for this. If you find something on my codepen that is listed public you can just use it. If you just use some technology behind it just copy and use as you like. If you want to embed a whole pen of mine (original creation) I'd love to get credits by linking my name :) Feel free to use it.

**Comment by wcat13** [comment]
To clarify you said something about having some ajax code and to contact you

https://codepen.io/MyXoToD/pen/BEFlL

I was just wanting to see that code.

**Comment by wcat13** [comment]
Not a big deal though so don't waste anytime as I have started looking into an alternative.

Thank you for replying

**Comment by MyXoToD** [comment]
Ohhh I see. Sorry but that code doesn't exist anymore. But it should be a good task to learn :) Learning ajax by building a chat is pretty easy and fun :) Good luck!
